language: python

# sudo false implies containerized builds, so we can use cacheing
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - CONDA_DEPS="pip flake8 pytest coverage numpy matplotlib pandas" PIP_DEPS="coveralls dipy nibabel pytest-cov boto3 scipy"

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
# Install conda only if necessary
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
- travis_retry pip install $PIP_DEPS

install:
- python setup.py install --record installed_files.txt

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v /doc/`

- py.test --pyargs AFQ --cov=AFQ --verbose

after_success:
- coveralls
