[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"
[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow to run (deselect with '--runslow')",
]
